### ISSUE TITLE
dotfiles and test issues

### ISSUE THREAD

**Issue by CodeDotJS** [geekodour/github-blog-api#1]
- I need a `.editorconfig` file of yours, otherwise, a lot of useless changes will happen in the whole codebase. 

- I wrote the new test but it even fails if we run it under `node version 5.5.0`. Though if we use `v6.6.0` there are no issues.

Reason - https://github.com/avajs/ava/issues/1354

- Also, add this project on `travis.ci`

**Comment by geekodour** [comment]
- please add the `.editorconfig` file, I'll not make any changes till then. 
- also, what should we do about the test fail? move to some simpler testing framework? 
the api code should work under nodev5.5 as `babel` is being used here.
- `travis.ci` yes will do that

**Comment by geekodour** [comment]
@CodeDotJS  I've added the `.editorconfig` file, I am not sure it's it's right. 
https://github.com/geekodour/github-blog-api/commit/6ca188665fcc012bf7f4cdf33207bfc94426b755
please check and push with corrections.

**Comment by CodeDotJS** [comment]
- About the `test`, well, let's stay with `ava` for now then we can move to `jest` if required. 

Also, its the issue with ava, not the code. So, depending upon the builds, we will decide if we use it or switch. 

Let me know when you put it on `travis.ci`
