### ISSUE TITLE
The API needs to handle exceptions and rejections properly

### ISSUE THREAD

**Issue by geekodour** [geekodour/github-blog-api#2]
Right now, exceptions and promise rejections are not being handled properly.
some are consoled out, some are thrown and some are just simply `reject`.
Need to handle exceptions and rejections properly, also need to see if the API request fails completely(eg.offline) then there should be a error for the `then` handler so that it can act upon it.

**Comment by geekodour** [comment]
I've added a fix to this, will post other issues related to exceptions here.

**Comment by CodeDotJS** [comment]
I guess, nearly all the issues related to handling exceptions and rejections are fixed. 

Should we close it?
